version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    versioning-strategy: auto
    labels:
      - "dependencies"
      - "security"
    # Only allow security updates to create PRs automatically
    # This will dramatically reduce the number of PRs
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
    # Group all non-major updates into a single PR
    groups:
      minor-patch-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
