version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    # Disable automatic pull requests completely
    open-pull-requests-limit: 0
    versioning-strategy: auto
    labels:
      - "dependencies"
      - "security"
    # Ignore all updates to prevent any PRs
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
