# GitHub Secret Scanning Configuration
# This file helps reduce false positives in secret scanning

paths-ignore:
  # Ignore files that contain regex patterns for secret detection
  - "app/utils/secureLogging.ts"
  - "docs/**/*.md"
  - "**/*.test.ts"
  - "**/*.test.js"
  - "config/jest.setup.js"
  - "tools/test-*.js"
  
  # Ignore example and template files
  - "**/*.example"
  - "**/*.template"
  - "**/examples/**"
  - "**/templates/**"

# Custom patterns to ignore (if supported in future)
patterns-ignore:
  # Ignore obvious test/mock patterns
  - "sk_test_mock"
  - "AIzaSyBJGLJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ"  # Test pattern
  - "your-api-key-here"
  - "your-secret-key-here"
