import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "@/providers/AuthProvider";
import MobileProvider from "@/providers/MobileProvider";
import AppProvider from "@/providers/AppProvider";
import { NextUIProvider } from "@nextui-org/react";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { Toaster } from "react-hot-toast"
import { DataProvider } from "@/providers/DataProvider";
import { GroupsProvider } from "@/providers/GroupsProvider";
import NextTopLoader from "nextjs-toploader";


const geistSans = localFont({
  src: "./fonts/Medium-Extended.ttf",
  variable: "--font-medium-extended",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased`}
      >
        <AppProvider>
          <ThemeProvider>
            <AuthProvider>
              <MobileProvider>
                <DataProvider>
                  <GroupsProvider>
                    <NextUIProvider>
                      <NextTopLoader />
                      {children}
                    </NextUIProvider>
                  </GroupsProvider>
                </DataProvider>
              </MobileProvider>
            </AuthProvider>
          </ThemeProvider>
        </AppProvider>
        <Toaster position="top-right"
          reverseOrder={false} />
      </body>
    </html>
  );
}
