import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "@/providers/AuthProvider";
import MobileProvider from "@/providers/MobileProvider";
import AppProvider from "@/providers/AppProvider";
import { NextUIProvider } from "@nextui-org/react";
import { ThemeProvider } from "@/providers/ThemeProvider";

const geistSans = localFont({
  src: "./fonts/Medium-Extended.ttf",
  variable: "--font-medium-extended",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased`}
      >
        <AppProvider>
          <ThemeProvider>
            <AuthProvider>
              <MobileProvider>
                <NextUIProvider>
                  {children}
                </NextUIProvider>
              </MobileProvider>
            </AuthProvider>
          </ThemeProvider>
        </AppProvider>
      </body>
    </html>
  );
}
