require_relative '../../node_modules/.bun/@capacitor+ios@7.4.4+1d43a6a1837411c8/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/.bun/@capacitor+ios@7.4.4+1d43a6a1837411c8/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/.bun/@capacitor+ios@7.4.4+1d43a6a1837411c8/node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/.bun/@capacitor+app@7.1.1+1d43a6a1837411c8/node_modules/@capacitor/app'
  pod 'CapacitorBrowser', :path => '../../node_modules/.bun/@capacitor+browser@7.0.3+1d43a6a1837411c8/node_modules/@capacitor/browser'
  pod 'CapacitorClipboard', :path => '../../node_modules/.bun/@capacitor+clipboard@7.0.3+1d43a6a1837411c8/node_modules/@capacitor/clipboard'
  pod 'CapacitorHaptics', :path => '../../node_modules/.bun/@capacitor+haptics@7.0.3+1d43a6a1837411c8/node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/.bun/@capacitor+keyboard@7.0.4+1d43a6a1837411c8/node_modules/@capacitor/keyboard'
  pod 'CapacitorNetwork', :path => '../../node_modules/.bun/@capacitor+network@7.0.3+1d43a6a1837411c8/node_modules/@capacitor/network'
  pod 'CapacitorPreferences', :path => '../../node_modules/.bun/@capacitor+preferences@7.0.3+1d43a6a1837411c8/node_modules/@capacitor/preferences'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/.bun/@capacitor+push-notifications@7.0.4+1d43a6a1837411c8/node_modules/@capacitor/push-notifications'
  pod 'CapacitorShare', :path => '../../node_modules/.bun/@capacitor+share@7.0.3+1d43a6a1837411c8/node_modules/@capacitor/share'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
